### ISSUE TITLE
Installed this package and not completing.

### ISSUE THREAD

**Issue by dentrinh** [osv/ac-html-bootstrap#3]
I tried to use this package but it doesn't seem to completing with bootstrap classes or fontawesome.  I only try to complete font awesome in the <i></i> tags as well.  Could an updated example be provided?  Thanks.

**Comment by osv** [comment]
What you use, `ac-html` or `company-web` (I use company-web)? Where you try to autocomplete, jade, html?

You can check my emacs repo for my web configuration. 

I don't enable it by default, so every new file I visit I use `company-web-bootstrap+` to enable it, also remeber, by default you need type 3 chars to fire autocomple :)

**Comment by dentrinh** [comment]
I use ac-html and I am trying to autocomplete html.
I will take a look at your configuration.  I might just switch over and use company-web at this point since it works for you.

Thanks for the friendly tip.  I remember ;)

**Comment by dentrinh** [comment]
Finally had some time to revisit this and I got it to play nicely with ac-html and company-web.  I set it up so that ac-html completes with auto-complete-mode and ac-html-bootstrap completes with company-mode/company-web.  Thanks for the help and neat package.

**Comment by osv** [comment]
Good to hear it :)
